/**
 * Constants and Configurations
 */

const FERIAS = {
    'centro': { name: 'Feria del Centro', handle: '@redcecosesola | FERIA DEL CENTRO' },
    'este': { name: 'Feria del Este', handle: '@redcecosesola | FERIA DEL ESTE' },
    'ruiz': { name: 'Feria de Ruiz Pineda', handle: '@redcecosesola | FERIA DE RUIZ PINEDA' },
    'Centro': { name: 'Feria del Centro', handle: '@redcecosesola | FERIA DEL CENTRO' },
    'Este': { name: 'Feria del Este', handle: '@redcecosesola | FERIA DEL ESTE' },
    'Ruiz Pineda': { name: 'Feria de Ruiz Pineda', handle: '@redcecosesola | FERIA DE RUIZ PINEDA' }
};

const PRESET_PRODUCTS = [
    "ACEITE DE COCO 180ML COCONUT",
  "ACEITE DE COCO 300ML",
  "ACEITE DE OLIVA CAPRI",
  "ACEITUNA RELLENA GIRALDA",
  "AFRECHO",
  "AGUACATE",
  "AJO CRIOLLO",
  "AJO PELADO",
  "ARANDANOS",
  "AVENA 8 DE MARZO",
  "AZUCAR MORENA",
  "BICARBONATO DE SODIO",
  "BOCADILLO DE GUAYABA",
  "BOCADILLO DE PLATANO",
  "BOROJO",
  "CAFÉ LO NUESTRO",
  "CAFÉ MATILDE",
  "CAMBUR",
  "CASABE",
  "CREMIGURT GRANDE GRIEGO",
  "CREMIGURT PEQUEÑO GRIEGO",
  "CEBOLLA MORADA",
  "CHAMPIÑON BANDEJA 200GR",
  "CHAMPIÑON DE VIDRIO 500GR",
  "CHIA PESADA",
  "CHOCOLATE ARTESANAL",
  "CIRUELA CRIOLLA",
  "CIRUELA IMPORTADA",
  "CURCUMA",
  "DURAZNO",
  "ESPINACA PAQUETE",
  "FRESAS",
  "FRESAS CONGELADA",
  "GRANOLA",
  "HUEVOS DE CODORNIZ",
  "JENGIBRE",
  "JUGO JUSTY",
  "KIWI",
  "LECHE DESLACTOSADA",
  "LIMON",
  "LULO",
  "MANDARINA CRIOLLA",
  "MANDARINA IMPORTADA",
  "MANI 200GR JUAN MARTINEZ",
  "MANI 85 JUAN MARTINEZ",
  "MANI MIXTO 100GR",
  "MANI MIXTO 200GR",
  "MANI MIXTO 500GR",
  "MANI SALADO Y NATURAL 100GR",
  "MANI SALADO Y NATURAL 200GR",
  "MANZANA AMARRILLA",
  "MANZANA ROJA 150",
  "MANZANA VERDE 100",
  "MANZANA VERDE 113",
  "MIEL SAN CARLOS",
  "MIGURT",
  "MIXTURA GRD",
  "MIXTURA PEQ",
  "MORA CONGELADA",
  "NARANJA IMPORTADA",
  "NARANJA TANYELO",
  "OBLEA",
  "ONOTO",
  "PALMERITAS Y PASTELITOS",
  "PAN ARABE",
  "PAN INTEGRAL",
  "PANELA DULCE",
  "PAPA COLOMBIANA",
  "PARCHITA",
  "PASA",
  "PASTA INTEGRAL",
  "PERA",
  "PIMENTON ROJO",
  "PITAHAYA AMARILLA/ROJA",
  "PULPA DE GUANABANA",
  "PULPA DE DURAZNO ENTROSO",
  "PULPA DE DURAZNO ETNA",
  "PULPA DE PARCHITA",
  "QUINOA PESADA",
  "REFRESCO GLUP",
  "SACOS",
  "SACOS PEQUEÑO",
  "TAMARINDO",
  "TOMATE",
  "TOMATE DE ARBOL",
  "TORTILLA DE MAIZ",
  "TURRON",
  "UCHUA",
  "UVA CRIOLLA",
  "UVA IMPORTADA",
  "VAINILLA",
  "VINAGRE DE MANZANA"
];

const PET_PRODUCTS = [
    "ARRO PICO 50*", "ARENA PESADA 50*", "ALPISTE 50*", "CERDO GENERICO", "CONVACA N 15",
    "INICIADOR P1", "GIRASOL", "ENGORDE EL TUNAL", "MAIZ AMARILLO", "MAIZ PICO",
    "MULTIPOLLO", "MULTIPONEDORA", "PONEDORA CORPO AGRO", "PONEDORA CONVACA",
    "VITALIN CONEJARINA", "POLVO PERUANO", "PRAXIMIDIVET", "SHAMPU HIPOLERGENICO",
    "SHAMPU PECARE", "SHAMPU PIGREE ADULTO", "SHAMPU VIMODOG", "SHAMPU YONG LIVING",
    "SPRAY GUSAVE", "SPRAY MATA CUCARACHA", "SPRAY MATA MOSCA", "STOP ANTI DERREICO",
    "TALCO PULGUISIDA", "ULTRA RAT RATICIDA", "VERMI OUT", "VITAMINA CHUMKY",
    "PERRARINA RINGO ADULTO", "PERRARINA RINGO CACHORRO", "PERRARINA DOG CHOW",
    "PERRAEINA K-NINA", "PERRAEINA SUPERCAN", "PERRARINA SUPERCAN CACHORRO",
    "PERARINA SUPERCAN CQT", "PERRARINA DOGURMET ADULTO", "PERRARINA DOGORMET CACHORRO",
    "PERRARINA FILPO", "PERRARINA ITALCAN", "PERRARINA TOP DOG", "PERRARINA CHAMP`S",
    "VITAMINA C VITANAMINA E", "GATARINA GATSY", "GATARINA CIPACAT", "GATARINA MIRRINGO ADULTO",
    "GATARINA MIRRINGO CACHORRO", "GATARINA MIRRINGO+PRO ADULTO", "GATARINA DON CAT",
    "OFTACSI GOTAS", "OMEGAKIN", "OREJAS DECERDO", "PAJARINA", "PAPILLA DE GATO",
    "PECHERA DE GATO", "PENTAVIVAL", "PEGA MOSCA", "PIPETA PERRO 11- A 20 KG"
];

const CHARCUTERIA_PRODUCTS = [
    "HUEVOS 1/2 ", "CASABE", "CHICHA GUARALAC 400GM", "CHORIZO AHUMADO", "CHULETA",
    "CREMA DON EUSTOQUIO 500 GR", "DIABLITO PLUMROSE", "DULCE DE LECHE", "GELATINA ARCOIRIS",
    "GELATINA ARCOIRIS GRANDE", "HELADO CHOCO MANI", "HELADO CHOCO MANTECADO",
    "HELADO CHOCO MOROCHO", "HELADO CONO CHICLE", "HELADO EXOTICO", "HELADO MAX POLET",
    "HELADO POLET FERRERO", "HELADO SUPER CONO", "HELADO TINITA", "HELADOS FRESS",
    "HUESO AHUMADO", "JAMON AHUMADO", "JAMON AREPERO", "JAMON DE PAVO", "JAMON ESPALDA ORST",
    "JAMON ESPALDA VIGOR", "JAMON PIERNA ARICHUNA", "JAMON PIERNA FIESTA", "JUGO GUARALAC 1.5ML",
    "JUGO GUARALAC 400CC", "JUGO GUARALAC 900CC", "JUGO JUSTY 1.5L", "LECHE PURISIMA COMPLETA",
    "LECHE PURISIMA DESCREMADA", "LECHE PURISIMA DESLACTOSADA", "LECHE SAN SIMON",
    "MARQUESAS", "MASA GRANDE", "MASAS PEQUEÑA", "MAX POÑLET WHITE FERRERO",
    "MINI SALCHICHAS FIESTA", "MORTADELA ALIBAL 1/2KG", "MORTADELA ALIBAL DE 1KG",
    "MORTADELA ALPRO 400G", "MORTADELA ALPRO 900G", "MORTADELA ARICHUNA", "MORTADELA BOLGNA 1/2KG",
    "MORTADELA CARACAS 900G", "MORTADELA ESPECIAL", "MORTADELA EXTRA", "MORTADELA PLUMROSE 1KG",
    "MORTADELA PUNTA DEL MONTE 1/2KG", "MORTADELA PUNTA DEL MONTE DE 1KG", "MORTADELA TAPARA",
    "NATILLA GUARALAC", "NATILLA VEGA", "PAN ARABE", "PAN DE SANDWICH INTEGRAL",
    "PAN DE SANDWICH NORMAL", "QUESILLO ARCOIRIS", "QUESO DE CABRA", "QUESO AMARILLO",
    "QUESO BLANCO", "QUESO CREMA DE CABRA", "QUESO CRINEJA", "QUESO DE AÑO POTE",
    "QUESO DE MANO POTE VERANO", "QUESO GUAYANEZ", "QUESO MOZZARELLA", "QUESO MOZZARELLA PIEZA",
    "QUESO PAISA", "QUESO PECORINO", "QUESO RAYADO", "QUESO REQUESON", "RECORTE CHULETA-TOCINETA",
    "RECORTE VARIOS", "REFRESCO GLUP 2L", "REFRESCO PEPSI 1.5 LT", "RICOTA CABRA BARAGUA",
    "RICOTA DE CABRA", "RICOTA POTE VERANO", "SALCHICA POLACA", "SALCHICHA DE POLLO ALPRO",
    "SUERO GUARALAC", "SUERO KASERO 850 ML", "SUERO PICANTE", "SUERO PICANTE PEQUE",
    "SUERO VEGA 800ML", "TOCINETA", "YOGUR ARCOIRIS GRAND", "YOGUR ARCOIRIS PEQ",
    "YOGURT GUARALAC 400 ML", "YOGURT NATURAL"
];

const UI_CONFIG = {
    'centro': {
        buttons: [
            { id: 'fruit', label: 'Frutería', icon: 'apple', color: '#f472b6', action: () => initPresets('fruit') },
            { id: 'char', label: 'Charcutería', icon: 'beef', color: '#3b82f6', action: () => window.location.href = 'charcuteria.html' }
        ]
    },
    'este': {
        buttons: [
            { id: 'fruit', label: 'Frutería', icon: 'apple', color: '#f472b6', action: () => initPresets('fruit') },
            { id: 'pet', label: 'Mascota', icon: 'dog', color: '#8b5cf6', action: () => initPresets('pet') },
            { id: 'char', label: 'Charcutería', icon: 'beef', color: '#3b82f6', action: () => initPresets('char') }
        ]
    },
    'ruiz': {
        buttons: [
            { id: 'fruit', label: 'Frutería', icon: 'apple', color: '#f472b6', action: () => initPresets('fruit') }
        ]
    }
};
